#!/bin/bash
searchKey=$1;
IFS_backup=$IFS
IFS=$'\n'
grepResult=($(find -type f | grep -n -r "$searchKey" .));
IFS=$IFS_backup

for element in "${grepResult[@]}"
#do git blame -e $element;
do
lineNumber=$(echo $element | cut -d\: -f2);
fileName=$(echo $element |cut -d\: -f1);
#echo $lineNumber;
#echo $fileName;
#do echo $element | cut -d: -f1 | git blame #log --format='%ae';
git blame -L$lineNumber,$lineNumber $fileName --format='%ae';
#echo $element|cut -d: -f2;
#git log -1 --format='%ae -L1,1 -e file
#
done
